---

## You must fill the empty variables

# Common

base_domain:
data_path: /data

user_uid_1000:
group_gid_1000: "{{ user_uid_1000 }}"

user_uid_33: www-data
group_gid_33: "{{ user_uid_33 }}"

docker_db_image: mariadb:10.3

## Following values will be used for the root account of every docker database
db_pass:
db_config_port: 3306

## anarres-sec

ssh_port: 2222

## Web and Let's Encrypt

nginx_processes: auto
web_ports_http: 80
web_ports_https: 443

web_path: /var/www

web_path_letsencrypt: "{{ web_path }}/letsencrypt"
web_path_default: "{{ web_path }}/default"

## Gitea

gitea_domain: "git.{{ base_domain }}"
gitea_docker_image: gitea/gitea:1.4

### DB

gitea_db_service_name: gitea-db
gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_user_pass:

gitea_directory:
  data: "{{ data_path }}/gitea/data"
  conf: "{{ data_path }}/gitea/data/gitea/conf"
gitea_ssh_port: 22
gitea_internal_web_port: 3000

## Transmission

transmission_domain: "torrent.{{ base_domain }}"
transmission_docker_image: linuxserver/transmission:latest
transmission_internal_web_port: 9091

transmission_user:
transmission_pass:

transmission_directory:
  conf: "{{ data_path }}/transmission/conf"
  downloads: "{{ data_path }}/transmission/downloads"
  watch: "{{ data_path }}/transmission/watch"

transmission_timezone:  # Example: Europe/Berlin

## Wallabag

wallabag_domain: "wallabag.{{ base_domain }}"
wallabag_docker_image: wallabag/wallabag:latest

wallabag_path_images: "{{ data_path }}/wallabag/images"

### DB

wallabag_db_service_name: wallabag-db
wallabag_db_name: wallabag
wallabag_db_user: wallabag
wallabag_db_user_pass:

wallabag_internal_web_port: 4000

## Selfoss

selfoss_domain: "selfoss.{{ base_domain }}"
selfoss_docker_image: hardware/selfoss:latest

selfoss_path_data: "{{ data_path }}/selfoss/data"

selfoss_internal_web_port: 4001


## Syncthing

syncthing_domain: "syncthing.{{ base_domain }}"
syncthing_docker_image: syncthing/syncthing:v0.14.48

syncthing_directory:
  conf: "{{ data_path }}/syncthing/config"
  data: "{{ data_path }}/syncthing"

syncthing_internal_web_port: 8384
syncthing_listening_port: 22000
syncthing_discovery_port: 21027

## OpenVPN

openvpn_domain: "openvpn.{{ base_domain }}"
openvpn_docker_image: kylemanna/openvpn:latest

openvpn_directory:
  conf: "{{ data_path }}/openvpn/conf"

openvpn_port: 1194
openvpn_protocol: udp

openvpn_ca_pass:
openvpn_ca_CN: "{{ openvpn_domain }}"

## Radicale

radicale_domain: "radicale.{{ base_domain }}"
radicale_docker_image: tomsquest/docker-radicale:amd64.2.1.10.2

radicale_user:
radicale_pass:

radicale_directory:
  data: "{{ data_path }}/radicale/data"
  etc: "{{ data_path }}/radicale/etc"
  conf: "{{ data_path }}/radicale/config"

radicale_internal_web_port: 5232

## taskd

taskd_domain: "{{ base_domain }}"
taskd_docker_image: andir/docker-taskd
taskd_port: 53589

taskd_directory:
  data: "{{ data_path }}/taskd/data"

## Nextcloud

nextcloud_domain: "cloud.{{ base_domain }}"
nextcloud_docker_image: nextcloud:14-apache
nextcloud_internal_web_port: 4001

nextcloud_directory:
  data: "{{ data_path }}/nextcloud/data"

### DB

nextcloud_db_service_name: nextcloud-db
nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud
nextcloud_db_user_pass:

## NFS

nfs_docker_image: erichough/nfs-server:latest

nfs_directory:
  export: "{{ data_path }}/nfs/export"
  conf: "{{ data_path }}/nfs/conf"

nfs_exports_conf: |
  /export       192.168.1.0/24(rw,fsid=0,no_subtree_check)

nfs_export_volumes: |
  -v {{ nfs_directory.export }}:/export:ro \
