---

## You must fill the empty variables

# Common

base_domain:
data_path: /data

user_uid_1000:
group_gid_1000: "{{ user_uid_1000 }}"

user_uid_33: www-data
group_gid_33: "{{ user_uid_33 }}"

ca_certs_path: /etc/ssl/certs/ca-certificates.crt

docker_db_image: mariadb:10.3
docker_db_postgres_image: postgres:11

## Following values will be used for the root account of every docker database
db_pass:
db_config_port: 3306

## anarres-sec

ssh_port: 2222

## Web and Let's Encrypt

nginx_processes: auto
web_ports_http: 80
web_ports_https: 443

web_path: /var/www

web_path_letsencrypt: "{{ web_path }}/letsencrypt"
web_path_default: "{{ web_path }}/default"

## OpenLDAP

openldap_domain: "{{ base_domain }}"
openldap_docker_image: osixia/openldap:1.2.3
openldap_port_secure: 636

openldap_directory:
  data: "{{ data_path }}/openldap/data"
  conf: "{{ data_path }}/openldap/conf"

openldap_organization:  # Example: anarres
openldap_base_DN:  # Example: dc=anarres,dc=local
openldap_admin_password:
openldap_readonly_password:

## OpenLDAP for services

openldap_server_protocol: 'ldaps://'
openldap_server_domain: "{{ base_domain }}"
openldap_server_port: 636
openldap_server_uri: "{{ openldap_server_protocol }}{{ openldap_server_domain }}:{{ openldap_server_port }}"
openldap_validate_certs: true
openldap_binddn: "cn=readonly,{{ openldap_base_DN }}"
openldap_bindcredentials: "{{ openldap_readonly_password }}"
openldap_searchbase: "ou=users,{{ openldap_base_DN }}"

## phpLDAPadmin

phpldapadmin_domain: "ldap.{{ base_domain }}"
phpldapadmin_docker_image: osixia/phpldapadmin:0.7.2
phpldapadmin_internal_web_port: 4002

phpldapadmin_ldap_hosts: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,{{ openldap_base_DN }}'}]}]}]"

## Gitea

gitea_domain: "git.{{ base_domain }}"
gitea_docker_image: gitea/gitea:1.6

### DB

gitea_db_service_name: gitea-db
gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_user_pass:

gitea_directory:
  data: "{{ data_path }}/gitea/data"
  conf: "{{ data_path }}/gitea/data/gitea/conf"
  git_data: "{{ data_path }}/gitea/data/git"
  ssh_data: "{{ data_path }}/gitea/data/ssh"

gitea_ssh_port: 22
gitea_internal_web_port: 3000
gitea_network: "gitea"

## Drone

drone_docker_image: drone/drone:1
drone_internal_web_port: 3030
drone_domain: "drone.{{ base_domain }}"

drone_directory:
  data: "{{ data_path }}/drone/data"

## Drone for GitHub

drone_github_docker_image: drone/drone:1
drone_github_internal_web_port: 3031
drone_github_domain: "drone-github.{{ base_domain }}"

drone_github_directory:
  data: "{{ data_path }}/drone_github/data"

drone_github_client_id:
drone_github_client_secret:

## CodiMD

codimd_docker_image: hackmdio/hackmd:1-alpine
codimd_domain: "codimd.{{ base_domain }}"
codimd_web_port: 3040
codimd_network_name: "codimd"

codimd_directory:
  db: "{{ data_path }}/codimd/db"
  uploads: "{{ data_path }}/codimd/uploads"

### DB

codimd_db_image: "{{ docker_db_postgres_image }}"
codimd_db_service_name: codimd-db
codimd_db_user: "codimd"
codimd_db_user_pass:
codimd_db_name: "codimd"

### LDAP

codimd_enable_ldap: true
codimd_ldap_url: "{{ openldap_server_uri }}"
codimd_ldap_binddn: "{{ openldap_binddn }}"
codimd_ldap_bindcredentials: "{{ openldap_bindcredentials }}"
codimd_ldap_searchbase: "{{ openldap_searchbase }}"
codimd_ldap_searchfilter: "{{ '(uid={{username}})' }}"
codimd_ldap_searchattributes: 'uid, mail'
codimd_ldap_userfield: 'uid'
codimd_ldap_usernamefield: 'uid'

## Transmission

transmission_domain: "torrent.{{ base_domain }}"
transmission_docker_image: linuxserver/transmission:163
transmission_internal_web_port: 9091
transmission_peer_port: 51413

transmission_user:
transmission_pass:

transmission_directory:
  conf: "{{ data_path }}/transmission/conf"
  downloads: "{{ data_path }}/transmission/downloads"
  watch: "{{ data_path }}/transmission/watch"

transmission_timezone:  # Example: Europe/Berlin

## Wallabag

wallabag_domain: "wallabag.{{ base_domain }}"
wallabag_docker_image: wallabag/wallabag:2.3.5

wallabag_path_images: "{{ data_path }}/wallabag/images"

### DB

wallabag_db_service_name: wallabag-db
wallabag_db_name: wallabag
wallabag_db_user: wallabag
wallabag_db_user_pass:

wallabag_internal_web_port: 4000

## Selfoss

selfoss_domain: "selfoss.{{ base_domain }}"
selfoss_docker_image: hardware/selfoss:2.1.8

selfoss_path_data: "{{ data_path }}/selfoss/data"

selfoss_internal_web_port: 4001


## Syncthing

syncthing_domain: "syncthing.{{ base_domain }}"
syncthing_docker_image: syncthing/syncthing:1.0.1
syncthing_directory:
  conf: "{{ data_path }}/syncthing/config"
  data: "{{ data_path }}/syncthing"

syncthing_internal_web_port: 8384
syncthing_listening_port: 22000
syncthing_discovery_port: 21027

## OpenVPN

openvpn_iptables_p2p_rule: "-A INPUT -p {{ openvpn_protocol }} -m state --state NEW -m {{ openvpn_protocol }} --dport {{ openvpn_port }} -j ACCEPT"
openvpn_confiure_docker_command: "docker run -v {{ openvpn_directory.conf }}:/etc/openvpn --rm {{ openvpn_docker_image }} ovpn_genconfig -u {{ openvpn_protocol }}://{{ openvpn_domain }}"
openvpn_create_ca_command: "docker run -v {{ openvpn_directory.conf }}:/etc/openvpn --rm -it {{ openvpn_docker_image }} ovpn_initpki"

openvpn_domain: "openvpn.{{ base_domain }}"
openvpn_docker_image: kylemanna/openvpn:latest

openvpn_directory:
  conf: "{{ data_path }}/openvpn/conf"

openvpn_port: 1194
openvpn_protocol: udp

openvpn_ca_pass:
openvpn_ca_CN: "{{ openvpn_domain }}"

## Radicale

radicale_domain: "radicale.{{ base_domain }}"
radicale_docker_image: tomsquest/docker-radicale:amd64.2.1.11.0

radicale_user:
radicale_pass:

radicale_directory:
  data: "{{ data_path }}/radicale/data"
  etc: "{{ data_path }}/radicale/etc"
  conf: "{{ data_path }}/radicale/config"

radicale_internal_web_port: 5232

## taskd

taskd_domain: "{{ base_domain }}"
taskd_docker_image: andir/docker-taskd:latest
taskd_port: 53589

taskd_directory:
  data: "{{ data_path }}/taskd/data"

## Nextcloud

nextcloud_domain: "cloud.{{ base_domain }}"
nextcloud_docker_image: nextcloud:15-apache
nextcloud_internal_web_port: 4001

nextcloud_directory:
  data: "{{ data_path }}/nextcloud/data"

### DB

nextcloud_db_service_name: nextcloud-db
nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud
nextcloud_db_user_pass:

## Taiga

taiga_domain: "taiga.{{ base_domain }}"
taiga_docker_image: local/taiga
taiga_internal_web_port: 3050
taiga_secret_key:

taiga_directory:
  media: "{{ data_path }}/taiga/media"
  db: "{{ data_path }}/taiga/db"

### DB

taiga_db_image: "{{ docker_db_postgres_image }}"
taiga_db_service_name: taiga-db
taiga_db_name: taiga
taiga_db_user: taiga
taiga_db_user_pass:

### LDAP

taiga_enable_ldap: true
taiga_ldap_server: "{{ openldap_server_protocol }}{{ openldap_server_domain }}"
taiga_ldap_port: "{{ openldap_server_port }}"
taiga_ldap_binddn: "{{ openldap_binddn }}"
taiga_ldap_bindcredentials: "{{ openldap_bindcredentials }}"
taiga_ldap_searchbase: "{{ openldap_searchbase }}"
taiga_ldap_search_property: 'uid'
taiga_ldap_email_attribute: 'mail'
taiga_ldap_full_name_attribute: 'cn'

## NFS

nfs_docker_image: erichough/nfs-server:1.2.0

# nfs_user_mounts:

nfs_directory:
  export: "{{ data_path }}/nfs/export"
  conf: "{{ data_path }}/nfs/conf"

nfs_exports_conf: |
  /export       192.168.1.0/24(ro,fsid=0,no_subtree_check)

nfs_export_volumes: |
  -v {{ nfs_directory.export }}:/export:ro \

## BIND DNS Server

user_uid_101: systemd-network

bind_dns_server_docker_image: sameersbn/bind:9.11.3-20190315
bind_dns_server_port: 53

bind_dns_server_directory:
  data: "{{ data_path }}/bind_dns_server/data"
