---

- name: Create openvpn CA
  vars:
    service_name: openvpn
  expect:
    command: "docker run -v {{ service_name }}:/etc/openvpn --rm -it {{ openvpn_docker_image}} ovpn_initpki"
    timeout: 600
    responses:
      "pass phrase": "{{ openvpn_ca_pass }}"
      "Common Name": "{{ openvpn_ca_CN }}"
