---

driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/default/.yamllint
platforms:
  - name: stretch
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
    groups:
      - anarres
provisioner:
  name: ansible
  playbooks:
    converge: ../../full.yml
  options:
    extra-vars:
      testing: true
      ssh_port: 22
      gitea_ssh_port: 77
      docker_registry_mirror: http://172.16.100.1:5000
  env:
    ANSIBLE_LIBRARY: /etc/ansible/library
    ANSIBLE_ROLES_PATH: ../../../../roles/
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../../
  lint:
    name: flake8
