---

driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/default/.yamllint
platforms:
  - name: stretch
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
    memory: 2048
    groups:
      - anarres
provisioner:
  name: ansible
  playbooks:
    converge: ../../full.yml
  options:
    extra-vars:
      testing: true
      docker_registry_mirror: http://172.16.100.1:5000
      ansible_become: true
      ansible_sudo: true
      user_uid_1000: vagrant
      base_domain: anarres.local
      db_pass: changeme
      ssh_port: 22
      registry_user: anarres
      registry_pass: changeme
      clair_db_user_pass: changeme
      openldap_organization: anarres
      openldap_base_DN: dc=anarres,dc=local
      openldap_admin_password: changeme
      openldap_readonly_password: changeme
      gitea_ssh_port: 66
      gitea_db_user_pass: changeme
      drone_github_client_id: placeholder
      drone_github_client_secret: placeholder
      codimd_db_user_pass: changeme
      transmission_user: transmission
      transmission_pass: transmission
      transmission_timezone: Europe/Berlin
      wallabag_db_user_pass: changeme
      openvpn_ca_pass: changeme
      nextcloud_db_user_pass: changeme
      taiga_secret_key: changeme
      taiga_db_user_pass: changeme
      user_uid_101: systemd-network
      influxdb_db: telegraf
      influxdb_admin_user: admin
      influxdb_admin_password: changeme
      influxdb_user: telegraf
      influxdb_user_password: changeme
      grafana_admin_pass: changeme
  lint:
    name: ansible-lint
    options:
      exclude:
        - roles/
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
