---
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Activate sysctl
  command: "sysctl -p /etc/sysctl.conf"
